Increment3
pavel-veber/metricsvr pull request #3
Opened 2022-08-08 08:26 UTC by pavel-veber

2022-08-10 16:28 UTC, tmvrus requested changes
Пожалуйста  внесите следующие изменения:
- разбить код на пакеты, это облегчит его чтение и пониманием границ ответственности
- избавьтесь от TODO, это дурной тон: они засоряют код (code smell)
- ознакомьтесь с ф-ей chi.URLParam она  поможет вам эффективней работать со параметрами
- постарайтесь всегда обрабатывать возвращаемые ошибки, как минимум их стоит логировать

2022-08-10 16:28 UTC, tmvrus commented on cmd/server/main.go
> +	tmpNewValue, err := strconv.ParseInt(v, 0, 64)
Что бы извлекать параметры запроса, воспользуйтесь ф-ей
```chi.URLParam```
это позволит вам избежать сложных  и небезопасных конструкций с разбиением строк

2022-08-10 16:28 UTC, tmvrus commented on cmd/server/main.go
> +	w.Write([]byte(strconv.Itoa(http.StatusNotImplemented)))
Write может вернуть ошибку, ее следует хотя бы логировать, для этого есть пакет log

2022-08-12 17:43 UTC, pavel-veber commented on cmd/agent/main.go
> +		}
Переписал с использованием Ticker+Sub.
metrics.Pull() - выполняю каждые pollInterval секунд т.к. так указано в ТЗ =)
```
# Инкремент 1
По умолчанию приложение должно обновлять метрики из пакета runtime с заданной частотой: pollInterval — 2 секунды.
По умолчанию приложение должно отправлять метрики на сервер с заданной частотой: reportInterval — 10 секунд.
```

2022-08-13 06:55 UTC, pavel-veber commented
> Пожалуйста  внесите следующие изменения:
> 
> * разбить код на пакеты, это облегчит его чтение и пониманием границ ответственности
> * избавьтесь от TODO, это дурной тон: они засоряют код (code smell)
> * ознакомьтесь с ф-ей chi.URLParam она  поможет вам эффективней работать со параметрами
> * постарайтесь всегда обрабатывать возвращаемые ошибки, как минимум их стоит логировать

- реструктурировал! Вроде чище стало
- TODO убрал
- chi.URLParam - прекрасен! Спасибо =)
- ошибки обрабатываю, пока только логирую

2022-08-16 12:35 UTC, tmvrus requested changes

2022-08-16 12:35 UTC, tmvrus commented on cmd/agent/agentLibs/metrics.go
> +	Gauge   map[string]Gauge
Вот эти поля сделаны экспортируемыми, возможно вам это не нужно

2022-08-16 12:35 UTC, tmvrus commented on cmd/agent/agentLibs/metrics.go
> +		Gauge:   make(map[string]Gauge),
вы бы могли сразу указать размер map, поскольку количество ключей фиксировано, в методу Pull они все перечислены

2022-08-16 12:35 UTC, tmvrus commented on cmd/agent/agentLibs/metrics.go
> +	listAllMetrics := make([]string, 0)
не стоит указывать тут 0, поскольку  длинна известна - это len(m.Counter)+len(m.Guage)
на учебных примерах разница вы не заметите, но указании размера является правилом хорошего тона и в реальных проектах разница в скорости будет заметной

2022-08-16 12:35 UTC, tmvrus commented on cmd/server/serverLibs/handlers.go
> +	w.WriteHeader(http.StatusOK)
этот статус библиотека запишет самостоятельно, это дефолтное поведение

2022-08-16 12:35 UTC, tmvrus commented on cmd/server/serverLibs/handlers.go
> +		log.Println(err)
после log.Println нужно добавить return иначе работа хендлера не прервется

2022-08-16 12:35 UTC, tmvrus commented on cmd/server/serverLibs/ramStorage.go
> +package serverLibs
в название пакетов обычно не добавляют Libs

2022-08-16 12:35 UTC, tmvrus commented on cmd/server/serverLibs/ramStorage.go
> +}
рекомендую вам упростить это условие, это повысит его читаемость 
```
if metricType == "counter" {
do work, return nil or error
}
if metricType == "gauge" { 
do work, return nil or error
}
return errors.New(fmt.Sprintf("unknown metric type: type=%v, name=%v", metricType, metricName))
```

таким образом вы разобьете уловие на три смысловых блока


еще рекомендую вынести 
`gauge` и `counter` в константы, так как они у вас используются в нескольких местах

2022-08-16 12:35 UTC, tmvrus commented on cmd/server/serverLibs/ramStorage.go
> +package serverLibs
в вашем случе вполне можно переименовать
agentLibs -> metrics
serverLibs -> metrics
поскольку в этих пакетах находится код работы с метрикаи

2022-08-16 12:35 UTC, tmvrus commented on cmd/server/serverLibs/ramStorage.go
> +	return fmt.Sprintf("<html><body>%v</body></html>", allMetrics)
такая множественная конкатенация строк, вызовет большое количество аллокаций, конкретно в вашем случае это не принципиально, но в будещем, рекомендую использовать более продвинутые методы
https://habr.com/ru/post/417479/

2022-08-17 11:18 UTC, pavel-veber commented on cmd/server/serverLibs/ramStorage.go
> +}
Спасибо! \m/

2022-08-17 11:21 UTC, pavel-veber commented on cmd/server/serverLibs/ramStorage.go
> +	return fmt.Sprintf("<html><body>%v</body></html>", allMetrics)
Из за сроков сделаю в следующем ПР

2022-08-17 11:22 UTC, pavel-veber commented
Все замечания учтены

2022-08-18 11:55 UTC, tmvrus approved these changes
Рекомендую вам на досуге написать тесты. Это вам облегчит внесение изменений в код в будущем.

2022-08-18 12:04 UTC, merged