Increment8 Check autotests
pavel-veber/metricsvr pull request #9
Opened 2022-08-30 10:40 UTC by pavel-veber

2022-09-05 15:50 UTC, rekby requested changes

2022-09-05 15:50 UTC, rekby commented on cmd/agent/metrics/metrics.go
>  	return make(MetricsSlice, 29)
Просто для информации - тут константа может легко разъехаться с количеством метрик.

Хорошо бы сделать тест на то что:
1. Массив заполняется (pull может пройти без паники)
2. Массив заполняется целиком - т.е. остаётся пустых элементов.
3.

2022-09-05 15:50 UTC, rekby commented on cmd/agent/metrics/metrics.go
> +func (m MetricsSlice) Report(metricServer string) {
Просто для информации: функцию отправки данных на сервер лучше отделить от метрик, т.к. метрики можно отправлять на сервер многими разными способами и метрика не обязана знать о каждом способе отправки.

2022-09-05 15:50 UTC, rekby commented on cmd/agent/main.go
>  		if sub >= *agentCfg.ReportInterval {
поллинг и отправку метрик на сервере лучше разделить на две горутины, т.к. сейчас не поддерживается ситуация когда ReportInterval меньше PollInterval

+ буду доп. задержки если PollInterval и ReportInterval не кратны друг другу.
Например PollInterval 2 секунды, а ReportInterval - 3 секунды.

2022-09-05 15:50 UTC, rekby commented on cmd/server/metrics/handlers.go
> +		if !strings.Contains(r.Header.Get("Accept-Encoding"), "gzip") {
тут gzip обнаружится только если будет стоять первым значением.

Если же клиент отправляет несколько поддерживаемых кодировок и gzip идёт не первым - то текущий код этого не поймёт и будет отправлять данные без сжатия.

Тут стоит воспользоваться r.Header.Values вместо r.Header.Get и проверить на gzip каждое значение.

2022-09-05 15:50 UTC, rekby commented on cmd/server/metrics/storage.go
>  type Storage interface {
Этот интерфейс слишком богаты для storage, например Backup используется для сохранения, но он потеряет смысл если поменять реализацию на базу данных.

Нужно удалить из интерфейса лишние методы и оставить только:
1. Сохранить метрику
2. Получить метрику
3. Получить все метрики (в типизированном виде метрик)

Сохранение в файл нужно унести внутрь реализации - чтобы код, внешний по отношению к хранилищу ничего об этом не знал (разве что на этапе создания экземпляра хранилища)

Формировать Html тоже нужно снаружи - в текущем виде для изменения формата ответа по всем метрикам придётся менять код метрик, хотя хранилище при этом может и не меняться.

Если вынести оформление во внешний код - то оформление можно менять не трогая кода сбора метрик с одной стороны, а с другой - при добавлении новых хранилищ не повторять код оформления в каждом варианте.

2022-09-05 15:55 UTC, rekby requested changes

2022-09-05 15:55 UTC, rekby commented on cmd/server/metrics/ramStorage.go
> +func (memStorage RamStorage) Update(metric Metrics) {
При чтении и обновлении метрик нужно использовать синхронизацию, иначе при одновременном обновлении нескольких метрик или обновлении и чтении метрик будут возникать гонки и данные могут оказаться испорченными.

2022-09-06 05:42 UTC, pavel-veber commented on cmd/server/metrics/ramStorage.go
> +func (memStorage RamStorage) Update(metric Metrics) {
А можно пример или ссылочку?)

2022-09-07 05:28 UTC, pavel-veber commented on cmd/agent/metrics/metrics.go
>  	return make(MetricsSlice, 29)
Из за сроков, на следующий спринт

2022-09-07 05:28 UTC, pavel-veber commented on cmd/agent/metrics/metrics.go
> +func (m MetricsSlice) Report(metricServer string) {
Из за сроков, на следующий спринт

2022-09-08 17:05 UTC, pavel-veber commented on cmd/server/metrics/ramStorage.go
> +func (memStorage RamStorage) Update(metric Metrics) {
Нашел что необходимо использовать sync.Mutex и sync.WaitGroup.
Из за сроков не успею поправить в этом ПР(небходимо почитать про sync.Mutex).

Если не критично, можно перенести на следующий спринт?

2022-09-13 08:32 UTC, merged